version: "3.9"
services:
  web:
    build: .
    container_name: ${PROJECT_CONTAINER}
    image: ${IMAGE_NAME}
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - mongo
    networks:
      - jenkins
  redis:
    container_name: REDIS_${PROJECT_CONTAINER}
    image: redis
    networks:
      - jenkins
  mongo:
    container_name: MONGO_${PROJECT_CONTAINER}
    image: mongo
    networks:
      - jenkins
networks:
  jenkins:
    name: jenkins