version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/code"
    networks:
      - task-scheduler-at
  redis:
    image: redis
    networks:
      - task-scheduler-at
  mongo:
    image: mongo
    networks:
      - task-scheduler-at
networks:
  task-scheduler-at:
    name: task-scheduler-at