version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/code"
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"