version: "3.9"
services:
  web:
    build: .
    container_name: APP_${PROJECT_CONTAINER}
    networks:
      - ts-at
  redis:
    image: redis
    networks:
      - ts-at
  mongo:
    image: mongo
    networks:
      - ts-at
networks:
  task-scheduler-at:
    name: ts-at
