version: "3.9"
services:
  web:
    build: .
    container_name: web_${PROJECT_NAME}-${TAG}
    image: ${NEXUS_IP_PORT}/${PROJECT_NAME}:${TAG}
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      - redis
      - mongo
    networks:
      - jenkins
  redis:
    container_name: redis_${PROJECT_NAME}-${TAG}
    image: redis
    networks:
      - jenkins
  mongo:
    container_name: mongo_${PROJECT_NAME}-${TAG}
    image: mongo
    networks:
      - jenkins
networks:
  jenkins:
    name: jenkins